# Generated by Django 4.2.6 on 2023-12-07 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='rate',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='subtotal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.product')),
            ],
        ),
    ]
