# Generated by Django 4.2.6 on 2023-12-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_productsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='size10_5',
            new_name='size_10',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size10',
            new_name='size_10h',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size11',
            new_name='size_11',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size6',
            new_name='size_6',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size6_5',
            new_name='size_6h',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size7',
            new_name='size_7',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size7_5',
            new_name='size_7h',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size8',
            new_name='size_8',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size8_5',
            new_name='size_8h',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size9',
            new_name='size_9',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size9_5',
            new_name='size_9h',
        ),
    ]
