# Generated by Django 4.2.6 on 2023-12-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_remove_product_return_policy_remove_product_warranty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
