# Generated by Django 4.2.6 on 2023-12-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_remove_product_size_cartproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
