# Generated by Django 4.2.6 on 2024-01-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0018_alter_cartproduct_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_10',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_10h',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_11',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_6',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_6h',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_7',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_7h',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_8',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_8h',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_9',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_9h',
            field=models.BooleanField(blank=True),
        ),
    ]
