# Generated by Django 4.2.6 on 2024-01-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0020_rename_sex_product_gioitinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='size_L',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='size_M',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='size_S',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='size_XL',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='size_XXL',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gioitinh',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
