# Generated by Django 4.2.6 on 2024-01-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0021_productsize_size_l_productsize_size_m_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gioitinh',
            new_name='sex',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_L',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_M',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_S',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_XL',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_XXL',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
