# Generated by Django 4.2.6 on 2024-01-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0022_rename_gioitinh_product_sex_alter_productsize_size_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
