# Generated by Django 4.2.6 on 2024-01-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0026_alter_product_line'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLine',
        ),
    ]
